### ISSUE TITLE
Example project crashes

### ISSUE THREAD

**Issue by jamezilla** [gsabran/DDDKit#3]
Blows up on unimplemented `public required init?(coder aDecoder: NSCoder)` in `DDDViewController`, immediately after startup.

![image](https://user-images.githubusercontent.com/19592/29348862-0f38cc64-821c-11e7-8990-ce9234430025.png)

**Comment by jamezilla** [comment]
Happens in both the latest release (1.3.0) and in the master branch.

**Comment by gsabran** [comment]
Thanks for reporting. I'll have a look

**Comment by HotdogWang** [comment]
Sorry, I also get this issue no matter on Simulator or Real iPhone.

**Comment by ThinkwikDev** [comment]
I've fixed the issue..
Remove below function from DDDView.swift 

    public required init?(coder aDecoder: NSCoder) {
        fatalError("DDDViewController should not be initialized from a coder")
    }

And add
    required public init(coder aDecoder: NSCoder) {
        self.isPaused = false
        DDDViewController.count += 1
        super.init(coder: aDecoder)!
    }

Thanks.

**Comment by gsabran** [comment]
Fixed by https://github.com/gsabran/DDDKit/commit/b348499aba58f170ffcc9154522b34a2d70af693, thanks for reporting!
